"""RL gateway: OpenAI-compatible proxy between the pi harness and the vLLM policy server.

Responsibilities
  * Route `model: "policy"` (whatever pi sends) to the current policy: the base model for version 0, the
    LoRA adapter `policy-v{N}` afterwards. New versions published by the trainer become active only at the
    next attempt boundary, so every rollout is generated by a single policy version.
  * RLTL;DR insight conditioning (paper Fig. 1 / App. A.2): for agent calls of the active attempt, insert one
    user message per insight right after the task (first user message):
        ==> A previous Attempt {i} on this same task FAILED the verifier. <==
        Hint on what went wrong: {hint}
  * Exact trajectory capture for training: request `return_token_ids` + `logprobs` from vLLM and append one
    record per LLM call (prompt ids, completion ids, behaviour logprobs, policy version, messages as sent)
    to data/attempts/<attempt_id>/calls.jsonl. Training never re-tokenizes chat text.
  * Robustness: waits for vLLM while it is down or restarting (pi only retries a few times), re-registers
    LoRA adapters lost by a vLLM restart, optional pause gate.

Control API (localhost only): GET /control/state, POST /control/attempt, /control/attempt_end,
/control/policy, /control/pause, /control/resume.
Headers on chat requests: X-RL-Kind (agent|insight|eval, default agent), X-RL-Attempt (override attempt id).
"""
import asyncio
import json
import logging
import os
import sys
import time
import uuid

import aiohttp
from aiohttp import web

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from rltldr.config import load_config  # noqa: E402
from rltldr.io_utils import append_jsonl, read_json, write_json_atomic  # noqa: E402

CFG = load_config()
STATE_PATH = CFG.path("gateway_state.json")
UPSTREAM_WAIT_S = 1800          # how long a request waits for a dead/restarting vLLM before failing
STALL_S = 900                   # a stream with no bytes for this long is treated as a wedged server
# Requests from the agent sandbox: only the fields pi sends; sampling is fixed to the policy's settings, so
# hand-made requests cannot inject off-policy samples into the training data.
SANDBOX_FIELDS = {"model", "messages", "tools", "tool_choice", "stream", "stream_options", "max_tokens",
                  "reasoning_effort", "parallel_tool_calls"}
SANDBOX_SAMPLING = {"temperature": 1.0, "top_p": 0.95, "top_k": 20, "min_p": 0.0, "presence_penalty": 0.0,
                    "repetition_penalty": 1.0, "n": 1}
SANDBOX_MAX_TOKENS = 32768
INSIGHT_HEADER = "==> A previous Attempt {i} on this same task FAILED the verifier. <=="
log = logging.getLogger("gateway")


def insight_message_text(idx: int, hint: str) -> str:
    return f"{INSIGHT_HEADER.format(i=idx)}\nHint on what went wrong: {hint}"


class State:
    def __init__(self):
        s = read_json(STATE_PATH, {}) or {}
        # policy = what new attempts use; pending = published by trainer, activated at next attempt start
        self.policy = s.get("policy") or {"name": CFG.base_model_name, "version": 0, "path": None}
        self.pending = s.get("pending")
        self.adapters = s.get("adapters", {})       # name -> path, for re-registration after vLLM restarts
        self.attempt = s.get("attempt")             # {"id", "insights": [{"idx","hint"}], "policy": {...}}
        self.paused = False
        self.gate = asyncio.Event()
        self.gate.set()
        self.lock = asyncio.Lock()

    def save(self):
        write_json_atomic(STATE_PATH, {"policy": self.policy, "pending": self.pending,
                                       "adapters": self.adapters, "attempt": self.attempt})

    def snapshot(self):
        return {"policy": self.policy, "pending": self.pending, "attempt": self.attempt,
                "paused": self.paused, "adapters": sorted(self.adapters)}


ST: State = None  # created inside the event loop
SESSION: aiohttp.ClientSession = None


# ------------------------------------------------------------------------------------------------------
# vLLM helpers
# ------------------------------------------------------------------------------------------------------
async def vllm_load_adapter(name: str, path: str) -> bool:
    try:
        async with SESSION.post(f"{CFG.vllm_url}/v1/load_lora_adapter",
                                json={"lora_name": name, "lora_path": path},
                                timeout=aiohttp.ClientTimeout(total=600)) as r:
            txt = await r.text()
            if r.status == 200 or "already" in txt.lower():
                return True
            log.error("load_lora_adapter %s failed: %s %s", name, r.status, txt[:300])
    except aiohttp.ClientError as e:
        log.error("load_lora_adapter %s error: %s", name, e)
    return False


async def vllm_unload_adapter(name: str) -> None:
    try:
        async with SESSION.post(f"{CFG.vllm_url}/v1/unload_lora_adapter", json={"lora_name": name},
                                timeout=aiohttp.ClientTimeout(total=120)) as r:
            await r.read()
    except aiohttp.ClientError:
        pass


async def vllm_served_models() -> set:
    async with SESSION.get(f"{CFG.vllm_url}/v1/models", timeout=aiohttp.ClientTimeout(total=10)) as r:
        d = await r.json()
    return {m["id"] for m in d.get("data", [])}


async def ensure_adapter_loaded(name: str) -> None:
    """Re-register an adapter that vLLM forgot (restart). No-op for the base model."""
    if name == CFG.base_model_name or name not in ST.adapters:
        return
    try:
        if name in await vllm_served_models():
            return
    except Exception:
        return
    log.warning("adapter %s missing in vLLM; re-loading from %s", name, ST.adapters[name])
    await vllm_load_adapter(name, ST.adapters[name])


# ------------------------------------------------------------------------------------------------------
# request rewriting
# ------------------------------------------------------------------------------------------------------
def inject_insights(messages: list, insights: list) -> tuple:
    """Insert one user message per insight right after the first user message (the task)."""
    if not insights:
        return messages, []
    first_user = next((i for i, m in enumerate(messages) if m.get("role") == "user"), None)
    if first_user is None:
        return messages, []
    texts = [insight_message_text(x["idx"], x["hint"]) for x in insights]
    new = messages[: first_user + 1] + [{"role": "user", "content": t} for t in texts] + messages[first_user + 1:]
    return new, [{"idx": x["idx"], "hint": x["hint"], "text": t} for x, t in zip(insights, texts)]


def merge_tool_call_deltas(acc: dict, deltas: list) -> None:
    for d in deltas or []:
        i = d.get("index", 0)
        tc = acc.setdefault(i, {"id": None, "type": "function", "function": {"name": "", "arguments": ""}})
        if d.get("id"):
            tc["id"] = d["id"]
        f = d.get("function") or {}
        if f.get("name"):
            tc["function"]["name"] += f["name"]
        if f.get("arguments"):
            tc["function"]["arguments"] += f["arguments"]


# ------------------------------------------------------------------------------------------------------
# main proxy endpoint
# ------------------------------------------------------------------------------------------------------
async def chat_completions(request: web.Request) -> web.StreamResponse:
    body = await request.json()
    trusted = request.app["trusted"]
    kind = request.headers.get("X-RL-Kind", "agent") if trusted else "agent"
    if not trusted:
        if not ST.attempt:
            return web.json_response({"error": "no active session"}, status=409)
        body = {k: v for k, v in body.items() if k in SANDBOX_FIELDS}
        body.update(SANDBOX_SAMPLING)
        body["max_tokens"] = min(int(body.get("max_tokens") or SANDBOX_MAX_TOKENS), SANDBOX_MAX_TOKENS)
    await ST.gate.wait()

    att = ST.attempt
    hdr_attempt = request.headers.get("X-RL-Attempt") if trusted else None
    attempt_id = hdr_attempt or (att["id"] if att else "no-attempt")
    # Policy: an attempt is pinned to the version active when it started; everything else uses current.
    pol = (att.get("policy") if att and attempt_id == att["id"] else None) or ST.policy
    injected = []
    if kind == "agent" and att and attempt_id == att["id"]:
        body["messages"], injected = inject_insights(body.get("messages", []), att.get("insights", []))

    body["model"] = pol["name"]
    body["return_token_ids"] = True
    body["logprobs"] = True
    body["top_logprobs"] = 0
    if body.get("tools") == []:            # vLLM >= 0.28 rejects an empty tools list
        body.pop("tools")
    stream = bool(body.get("stream"))
    if stream:
        body.setdefault("stream_options", {})["include_usage"] = True

    rec = {"call_id": uuid.uuid4().hex[:12], "kind": kind, "attempt_id": attempt_id,
           "policy": {"name": pol["name"], "version": pol["version"]}, "t0": time.time(),
           "injected": injected, "messages": body.get("messages"), "tools": body.get("tools"),
           "params": {k: body.get(k) for k in ("temperature", "top_p", "top_k", "min_p", "max_tokens",
                                               "reasoning_effort", "chat_template_kwargs",
                                               "presence_penalty", "repetition_penalty",
                                               "thinking_token_budget")}}
    calls_path = CFG.path("attempts", attempt_id, "calls.jsonl")

    upstream = await open_upstream(body)
    if isinstance(upstream, web.Response):      # gave up waiting for vLLM
        rec.update(status="upstream_unavailable", t1=time.time())
        append_jsonl(calls_path, rec)
        return upstream
    try:
        if upstream.status != 200:
            txt = await upstream.text()
            rec.update(status=f"http_{upstream.status}", error=txt[:2000], t1=time.time())
            append_jsonl(calls_path, rec)
            return web.Response(status=upstream.status, text=txt, content_type="application/json")
        if not stream:
            d = await upstream.json()
            c = d["choices"][0]
            rec.update(prompt_ids=d.get("prompt_token_ids"), completion_ids=c.get("token_ids"),
                       logprobs=[x["logprob"] for x in ((c.get("logprobs") or {}).get("content") or [])],
                       finish_reason=c.get("finish_reason"), usage=d.get("usage"),
                       response=c.get("message"), status="ok", t1=time.time())
            append_jsonl(calls_path, rec)
            return web.json_response(d)
        return await relay_stream(request, upstream, rec, calls_path)
    finally:
        upstream.release()


async def open_upstream(body: dict):
    """POST to vLLM, waiting out restarts and re-registering a missing adapter once."""
    deadline = time.time() + UPSTREAM_WAIT_S
    delay, reloaded = 2.0, False
    while True:
        try:
            r = await SESSION.post(f"{CFG.vllm_url}/v1/chat/completions", json=body,
                                   timeout=aiohttp.ClientTimeout(total=None, sock_connect=10))
        except (aiohttp.ClientConnectionError, asyncio.TimeoutError) as e:
            if time.time() > deadline:
                return web.json_response({"error": f"vLLM unavailable: {e}"}, status=503)
            log.warning("vLLM unreachable (%s); retrying in %.0fs", e, delay)
            await asyncio.sleep(delay)
            delay = min(delay * 1.5, 30)
            continue
        if r.status == 404 and not reloaded and body["model"] != CFG.base_model_name:
            txt = await r.text()
            r.release()
            log.warning("404 for %s (%s); re-registering adapter", body["model"], txt[:200])
            await ensure_adapter_loaded(body["model"])
            reloaded = True
            continue
        return r


async def relay_stream(request, upstream, rec, calls_path):
    resp = web.StreamResponse(status=200, headers={"Content-Type": "text/event-stream",
                                                   "Cache-Control": "no-cache"})
    await resp.prepare(request)
    prompt_ids, ids, lps, fin, usage = None, [], [], None, None
    content, reasoning, tool_acc = [], [], {}
    buf = b""
    status = "ok"
    client_gone = False
    try:
        while True:
            try:
                chunk = await asyncio.wait_for(upstream.content.readany(), timeout=STALL_S)
            except asyncio.TimeoutError:
                status = "upstream_stalled"
                log.error("stream for call %s stalled for %ds; aborting", rec["call_id"], STALL_S)
                break
            if not chunk:
                break
            if not client_gone:
                try:
                    await resp.write(chunk)
                except (ConnectionResetError, aiohttp.ClientConnectionError):
                    # pi hangs up right after the final event; keep draining upstream so the record is
                    # complete (a genuine abort is detected below by the missing finish_reason)
                    client_gone = True
            buf += chunk
            while b"\n\n" in buf:
                ev, buf = buf.split(b"\n\n", 1)
                for line in ev.split(b"\n"):
                    if not line.startswith(b"data: ") or line[6:].strip() == b"[DONE]":
                        continue
                    try:
                        d = json.loads(line[6:])
                    except json.JSONDecodeError:
                        continue
                    prompt_ids = prompt_ids or d.get("prompt_token_ids")
                    usage = d.get("usage") or usage
                    for c in d.get("choices", []):
                        ids += c.get("token_ids") or []
                        lps += [x["logprob"] for x in ((c.get("logprobs") or {}).get("content") or [])]
                        fin = c.get("finish_reason") or fin
                        dl = c.get("delta") or {}
                        if dl.get("content"):
                            content.append(dl["content"])
                        r = dl.get("reasoning") or dl.get("reasoning_content")
                        if r:
                            reasoning.append(r)
                        merge_tool_call_deltas(tool_acc, dl.get("tool_calls"))
                if client_gone and fin is not None and usage is not None:
                    break                # everything needed is recorded; stop the generation
        if not client_gone and status == "ok":
            try:
                await resp.write_eof()
            except (ConnectionResetError, aiohttp.ClientConnectionError):
                pass
        if client_gone and fin is None:
            status = "aborted:client_disconnected"
    except (ConnectionResetError, aiohttp.ClientConnectionError, asyncio.CancelledError) as e:
        status = f"aborted:{type(e).__name__}"   # upstream died, or the request task was cancelled
    rec.update(prompt_ids=prompt_ids, completion_ids=ids, logprobs=lps, finish_reason=fin, usage=usage,
               response={"role": "assistant", "content": "".join(content) or None,
                         "reasoning": "".join(reasoning) or None,
                         "tool_calls": [tool_acc[i] for i in sorted(tool_acc)] or None},
               status=status, t1=time.time())
    if status == "ok" and len(ids) != len(lps):
        rec["status"] = "ok_logprob_mismatch"
    append_jsonl(calls_path, rec)
    return resp


# ------------------------------------------------------------------------------------------------------
# control endpoints
# ------------------------------------------------------------------------------------------------------
async def ctl_state(_):
    return web.json_response(ST.snapshot())


async def ctl_attempt(request):
    """Start an attempt: activates a pending policy version, sets insights to inject."""
    d = await request.json()
    async with ST.lock:
        if ST.pending:
            old = ST.policy
            ST.policy, ST.pending = ST.pending, None
            log.info("activated policy %s (was %s)", ST.policy["name"], old["name"])
            # keep current + previous loaded; unload older adapters to bound vLLM CPU/GPU LoRA slots
            for name in list(ST.adapters):
                v = int(name.rsplit("-v", 1)[1]) if "-v" in name else -1
                if v < ST.policy["version"] - 1:
                    await vllm_unload_adapter(name)
                    ST.adapters.pop(name)
        await ensure_adapter_loaded(ST.policy["name"])
        ST.attempt = {"id": d["id"], "insights": d.get("insights", []), "policy": dict(ST.policy),
                      "t0": time.time()}
        ST.save()
    return web.json_response(ST.snapshot())


async def ctl_attempt_end(request):
    d = await request.json()
    async with ST.lock:
        if ST.attempt and ST.attempt["id"] == d.get("id"):
            ST.attempt = None
            ST.save()
    return web.json_response(ST.snapshot())


async def ctl_policy(request):
    """Register a newly trained policy version (pending until the next attempt starts)."""
    d = await request.json()
    name, path, version = d["name"], d["path"], int(d["version"])
    ok = await vllm_load_adapter(name, path)
    if not ok:
        return web.json_response({"error": f"vLLM failed to load {name}"}, status=500)
    async with ST.lock:
        ST.adapters[name] = path
        ST.pending = {"name": name, "version": version, "path": path}
        if d.get("activate_now"):
            ST.policy, ST.pending = ST.pending, None
        ST.save()
    return web.json_response(ST.snapshot())


async def ctl_pause(_):
    ST.paused = True
    ST.gate.clear()
    return web.json_response(ST.snapshot())


async def ctl_resume(_):
    ST.paused = False
    ST.gate.set()
    return web.json_response(ST.snapshot())


async def models(_):
    return web.json_response({"object": "list", "data": [
        {"id": "policy", "object": "model", "owned_by": "rltldr", "root": ST.policy["name"]}]})


async def health(_):
    return web.json_response({"ok": True})


async def startup():
    global ST, SESSION
    ST = State()
    SESSION = aiohttp.ClientSession(connector=aiohttp.TCPConnector(limit=0))
    log.info("gateway up; policy=%s pending=%s", ST.policy, ST.pending)


def make_app(trusted: bool) -> web.Application:
    app = web.Application(client_max_size=1 << 31)
    app["trusted"] = trusted
    routes = [web.post("/v1/chat/completions", chat_completions), web.get("/v1/models", models),
              web.get("/health", health)]
    if trusted:
        routes += [web.get("/control/state", ctl_state), web.post("/control/attempt", ctl_attempt),
                   web.post("/control/attempt_end", ctl_attempt_end), web.post("/control/policy", ctl_policy),
                   web.post("/control/pause", ctl_pause), web.post("/control/resume", ctl_resume)]
    app.add_routes(routes)
    return app


async def serve():
    await startup()
    # trusted: TCP on localhost (driver, trainer, operator). untrusted: Unix socket forwarded into the agent
    # sandbox as 127.0.0.1:8100 — chat completions only, no control endpoints, no X-RL-* headers.
    sock = os.path.join(CFG.run_dir, "gateway.sock")
    os.makedirs(os.path.dirname(sock), exist_ok=True)
    if os.path.exists(sock):
        os.unlink(sock)
    runners = []
    for trusted, site in ((True, lambda r: web.TCPSite(r, CFG.gateway_host, CFG.gateway_port)),
                          (False, lambda r: web.UnixSite(r, sock))):
        r = web.AppRunner(make_app(trusted), access_log=None)
        await r.setup()
        await site(r).start()
        runners.append(r)
    log.info("listening on %s:%d (trusted) and %s (sandbox)", CFG.gateway_host, CFG.gateway_port, sock)
    try:
        await asyncio.Event().wait()
    finally:
        for r in runners:
            await r.cleanup()
        await SESSION.close()


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    asyncio.run(serve())


if __name__ == "__main__":
    main()
